### ISSUE TITLE
[PE-D][Tester B] The Constraints in Using dd/MM/yy

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-2/tp#194]
Imagine today is year 31/12/2099, tomorrow is going to be before today.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: alexgoexercise/ped#10

**Comment by jinxuan-owyong** [comment]
This issue is highly opinionated and will not be considered as a bug for the application.

As highlighted in the [`SimpleDateFormat` API](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html), 
> For parsing with the abbreviated year pattern ("y" or "yy"), SimpleDateFormat must interpret the abbreviated year relative to some century. It does this by adjusting dates to be within 80 years before and 20 years after the time the SimpleDateFormat instance is created.

the following command would result in an error since it is ambiguous:
`/view -sd 01/01/43 -ed 31/12/19`

As such, it would be good to highlight this behaviour to the user in the user guide.

**Comment by jinxuan-owyong** [comment]
The most recent update for the user guide may be confusing to users who are not familiar with reading documentation. As such, it would be clearer to highlight the exact behaviour of the `/edit` implementation using examples.
For example, `/view -ed 13/12/99 -sd 13/12/23` does not result in an error, even though the user may want to filter entries from 13th December 1999 to 13th December 2023. However, the  start and end date filters are mixed up, which the application interprets as filtering from 13th December 2023 to 13th December 2099 and does not give an error message.
